<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'LammStorage\Tests\ModuleTest'                        => __DIR__ . '/test/LammStorage/ModuleTest.php',
  'LammStorage\Tests\BaseModuleTest'                    => __DIR__ . '/test/LammStorage/BaseModuleTest.php',
  'LammStorage\Tests\Session\SaveHandler\RedisTest'     => __DIR__ . '/test/LammStorage/src/Session/SaveHandler/RedisTest.php',
  'LammStorage\Tests\Service\SessionManagerFactoryTest' => __DIR__ . '/test/LammStorage/src/Service/SessionManagerFactoryTest.php',
  'LammStorage\Tests\Adapter\RedisAdapterTest'          => __DIR__ . '/test/LammStorage/src/Adapter/RedisAdapterTest.php',
  'LammStorage\Tests\Bootstrap'                         => __DIR__ . '/test/Bootstrap.php',
  'LammStorage\Session\SaveHandler\Redis'               => __DIR__ . '/src/LammStorage/Session/SaveHandler/Redis.php',
  'LammStorage\Cache\Storage\Adapter\Redis'             => __DIR__ . '/src/LammStorage/Cache/Storage/Adapter/Redis.php',
  'LammStorage\Service\SessionManagerFactory'           => __DIR__ . '/src/LammStorage/Service/SessionManagerFactory.php',
  'LammStorage\Module'                                  => __DIR__ . '/Module.php',
);
